package metrics

type MonitorCurrent struct {
	Connections     int64 `json:"connections"`
	DroppedMsgRate  int64 `json:"dropped_msg_rate"`
	LiveConnections int64 `json:"live_connections"`
	ReceivedMsgRate int64 `json:"received_msg_rate"`
	SentMsgRate     int64 `json:"sent_msg_rate"`
	Subscriptions   int64 `json:"subscriptions"`
	Topics          int64 `json:"topics"`
}

type Monitor struct {
	Connections     int64 `json:"connections"`
	Dropped         int64 `json:"dropped"`
	LiveConnections int64 `json:"live_connections"`
	Received        int64 `json:"received"`
	Sent            int64 `json:"sent"`
	Subscriptions   int64 `json:"subscriptions"`
	TimeStamp       int64 `json:"time_stamp"`
	Topics          int64 `json:"topics"`
}

type Stats struct {
	ChannelsCount            int64  `json:"channels.count"`
	ChannelsMax              int64  `json:"channels.max"`
	ConnectionsCount         int64  `json:"connections.count"`
	ConnectionsMax           int64  `json:"connections.max"`
	DelayedCount             int64  `json:"delayed.count"`
	DelayedMax               int64  `json:"delayed.max"`
	LiveConnectionsCount     int64  `json:"live_connections.count"`
	LiveConnectionsMax       int64  `json:"live_connections.max"`
	Node                     string `json:"node"`
	RetainedCount            int64  `json:"retained.count"`
	RetainedMax              int64  `json:"retained.max"`
	SessionsCount            int64  `json:"sessions.count"`
	SessionsMax              int64  `json:"sessions.max"`
	SuboptionsCount          int64  `json:"suboptions.count"`
	SuboptionsMax            int64  `json:"suboptions.max"`
	SubscribersCount         int64  `json:"subscribers.count"`
	SubscribersMax           int64  `json:"subscribers.max"`
	SubscriptionsCount       int64  `json:"subscriptions.count"`
	SubscriptionsMax         int64  `json:"subscriptions.max"`
	SubscriptionsSharedCount int64  `json:"subscriptions.shared.count"`
	SubscriptionsSharedMax   int64  `json:"subscriptions.shared.max"`
	TopicsCount              int64  `json:"topics.count"`
	TopicsMax                int64  `json:"topics.max"`
}

type Metrics struct {
	AuthenticationSuccess             int64  `json:"authentication.success"`
	MessagesQoS1Sent                  int64  `json:"messages.qos1.sent"`
	PacketsUnsubackSent               int64  `json:"packets.unsuback.sent"`
	PacketsConnectReceived            int64  `json:"packets.connect.received"`
	PacketsAuthReceived               int64  `json:"packets.auth.received"`
	PacketsPubackReceived             int64  `json:"packets.puback.received"`
	PacketsPubcompSent                int64  `json:"packets.pubcomp.sent"`
	MessagesPublish                   int64  `json:"messages.publish"`
	OverloadProtectionGC              int64  `json:"overload_protection.gc"`
	PacketsPubcompReceived            int64  `json:"packets.pubcomp.received"`
	MessagesQoS0Received              int64  `json:"messages.qos0.received"`
	AuthorizationSuperuser            int64  `json:"authorization.superuser"`
	DeliveryDropped                   int64  `json:"delivery.dropped"`
	DeliveryDroppedNoLocal            int64  `json:"delivery.dropped.no_local"`
	OverloadProtectionDelayOK         int64  `json:"overload_protection.delay.ok"`
	OverloadProtectionNewConn         int64  `json:"overload_protection.new_conn"`
	PacketsPublishDropped             int64  `json:"packets.publish.dropped"`
	ClientAuthorize                   int64  `json:"client.authorize"`
	PacketsPublishReceived            int64  `json:"packets.publish.received"`
	MessagesDroppedAwaitPubrelTimeout int64  `json:"messages.dropped.await_pubrel_timeout"`
	BytesSent                         int64  `json:"bytes.sent"`
	ClientAuthAnonymous               int64  `json:"client.auth.anonymous"`
	AuthenticationFailure             int64  `json:"authentication.failure"`
	SessionDiscarded                  int64  `json:"session.discarded"`
	OverloadProtectionHibernation     int64  `json:"overload_protection.hibernation"`
	PacketsPubrecInuse                int64  `json:"packets.pubrec.inuse"`
	MessagesDelayed                   int64  `json:"messages.delayed"`
	BytesReceived                     int64  `json:"bytes.received"`
	PacketsPublishAuthError           int64  `json:"packets.publish.auth_error"`
	MessagesDelivered                 int64  `json:"messages.delivered"`
	AuthorizationCacheHit             int64  `json:"authorization.cache_hit"`
	MessagesDropped                   int64  `json:"messages.dropped"`
	ClientAuthenticate                int64  `json:"client.authenticate"`
	PacketsSubscribeError             int64  `json:"packets.subscribe.error"`
	PacketsPubrecSent                 int64  `json:"packets.pubrec.sent"`
	AuthorizationMatchedAllow         int64  `json:"authorization.matched.allow"`
	PacketsPingreqReceived            int64  `json:"packets.pingreq.received"`
	PacketsSubscribeReceived          int64  `json:"packets.subscribe.received"`
	PacketsReceived                   int64  `json:"packets.received"`
	MessagesAcked                     int64  `json:"messages.acked"`
	PacketsPubrecReceived             int64  `json:"packets.pubrec.received"`
	PacketsConnackError               int64  `json:"packets.connack.error"`
	PacketsUnsubscribeError           int64  `json:"packets.unsubscribe.error"`
	MessagesQoS2Sent                  int64  `json:"messages.qos2.sent"`
	SessionResumed                    int64  `json:"session.resumed"`
	Node                              string `json:"node"`
	PacketsPubackMissed               int64  `json:"packets.puback.missed"`
	MessagesForward                   int64  `json:"messages.forward"`
	PacketsDisconnectSent             int64  `json:"packets.disconnect.sent"`
	PacketsPubrecMissed               int64  `json:"packets.pubrec.missed"`
	PacketsPubackInuse                int64  `json:"packets.puback.inuse"`
	PacketsAuthSent                   int64  `json:"packets.auth.sent"`
	MessagesQoS2Received              int64  `json:"messages.qos2.received"`
	PacketsSent                       int64  `json:"packets.sent"`
	ClientSubscribe                   int64  `json:"client.subscribe"`
	PacketsConnackAuthError           int64  `json:"packets.connack.auth_error"`
	PacketsPubrelMissed               int64  `json:"packets.pubrel.missed"`
	DeliveryDroppedTooLarge           int64  `json:"delivery.dropped.too_large"`
	AuthenticationSuccessAnonymous    int64  `json:"authentication.success.anonymous"`
	PacketsPubackSent                 int64  `json:"packets.puback.sent"`
	MessagesDroppedNoSubscribers      int64  `json:"messages.dropped.no_subscribers"`
	PacketsPubcompInuse               int64  `json:"packets.pubcomp.inuse"`
	MessagesQoS0Sent                  int64  `json:"messages.qos0.sent"`
	MessagesSent                      int64  `json:"messages.sent"`
	PacketsUnsubscribeReceived        int64  `json:"packets.unsubscribe.received"`
	PacketsConnackSent                int64  `json:"packets.connack.sent"`
	PacketsSubscribeAuthError         int64  `json:"packets.subscribe.auth_error"`
	PacketsPingrespSent               int64  `json:"packets.pingresp.sent"`
	DeliveryDroppedExpired            int64  `json:"delivery.dropped.expired"`
	AuthorizationNomatch              int64  `json:"authorization.nomatch"`
	PacketsPubrelReceived             int64  `json:"packets.pubrel.received"`
	SessionCreated                    int64  `json:"session.created"`
	PacketsDisconnectReceived         int64  `json:"packets.disconnect.received"`
	ClientConnack                     int64  `json:"client.connack"`
	AuthorizationMatchedDeny          int64  `json:"authorization.matched.deny"`
	PacketsPubcompMissed              int64  `json:"packets.pubcomp.missed"`
	AuthorizationAllow                int64  `json:"authorization.allow"`
	PacketsPublishInuse               int64  `json:"packets.publish.inuse"`
	SessionTakenover                  int64  `json:"session.takenover"`
	OverloadProtectionDelayTimeout    int64  `json:"overload_protection.delay.timeout"`
	DeliveryDroppedQueueFull          int64  `json:"delivery.dropped.queue_full"`
	DeliveryDroppedQoS0Msg            int64  `json:"delivery.dropped.qos0_msg"`
	SessionTerminated                 int64  `json:"session.terminated"`
	ClientConnected                   int64  `json:"client.connected"`
	ClientUnsubscribe                 int64  `json:"client.unsubscribe"`
	AuthorizationDeny                 int64  `json:"authorization.deny"`
	PacketsPubrelSent                 int64  `json:"packets.pubrel.sent"`
	PacketsPublishSent                int64  `json:"packets.publish.sent"`
	PacketsPublishError               int64  `json:"packets.publish.error"`
	MessagesReceived                  int64  `json:"messages.received"`
	MessagesQoS1Received              int64  `json:"messages.qos1.received"`
	ClientDisconnected                int64  `json:"client.disconnected"`
	PacketsSubackSent                 int64  `json:"packets.suback.sent"`
	ClientConnect                     int64  `json:"client.connect"`
}
